const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const totalProducts=112,pageSize=24;let visibleProducts=pageSize,activeFilter='all';const productGrid=document.querySelector('#product-grid');const loadMore=document.querySelector('#load-more');const categories=['allround','touring','yoga','fishing'];const series=['Coast','Drift','Voyager','Lagoon','Current','Horizon','Marina','Explorer'];
const products=Array.from({length:totalProducts},(_,index)=>({index,name:`${series[index%series.length]} SUP ${String(index+1).padStart(3,'0')}`,category:categories[index%categories.length],price:888}));
function productMarkup(product){const col=product.index%8,row=Math.floor(product.index/8),x=(col/7*100).toFixed(4),y=(row/13*100).toFixed(4),label=product.category==='allround'?'ALL-ROUND':product.category.toUpperCase();return `<article class="product-card visible" data-category="${product.category}" data-name="${product.name}" data-price="888"><div class="product-image catalog-image" style="background-position:${x}% ${y}%"><span class="badge">${product.index<8?'NEW CATALOG':'COMPLETE KIT'}</span><button class="quick" aria-label="Quick view ${product.name}">＋</button></div><div class="product-info"><div><p>${label} / INFLATABLE SUP</p><h3>${product.name}</h3></div><strong>€888</strong></div><div class="catalog-note">Board + paddle + pump + leash + bag</div></article>`}
function renderProducts(){const matching=products.filter(p=>activeFilter==='all'||p.category===activeFilter);productGrid.innerHTML=matching.slice(0,visibleProducts).map(productMarkup).join('');document.querySelector('#catalog-count').textContent=`${matching.length} paddle boards`;loadMore.hidden=visibleProducts>=matching.length;bindQuickViews()}
document.querySelectorAll('.filters button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');button.classList.add('active');activeFilter=button.dataset.filter;visibleProducts=pageSize;renderProducts()}));loadMore.addEventListener('click',()=>{visibleProducts+=pageSize;renderProducts()});
const dialog=document.querySelector('#quick-dialog');const dialogName=document.querySelector('#dialog-name');const dialogPrice=document.querySelector('#dialog-price');let selectedProduct=null;function bindQuickViews(){document.querySelectorAll('.quick').forEach(button=>button.addEventListener('click',()=>{selectedProduct=button.closest('.product-card');dialogName.textContent=selectedProduct.dataset.name;dialogPrice.textContent='€888';dialog.showModal()}))}document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});renderProducts();
let bag=0;const bagCount=document.querySelector('#bag-count');const toast=document.querySelector('#toast');document.querySelector('.add-button').addEventListener('click',()=>{bag+=1;bagCount.textContent=bag;dialog.close();toast.textContent=`${selectedProduct.dataset.name} added to your bag`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)});
document.querySelector('#newsletter-form').addEventListener('submit',event=>{event.preventDefault();const status=document.querySelector('#form-status');status.textContent='Welcome aboard — check your inbox.';event.target.reset()});
